# Generated by Django 3.2.23 on 2024-01-01 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dmg7oqpgs/image/upload/v1704034646/static/images/avatar.b2e01619cc46.png', max_length=255, verbose_name='image'),
        ),
    ]
