# Generated by Django 3.2.23 on 2023-11-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
