# Generated by Django 3.2.23 on 2023-11-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20231127_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['profile']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
