# Generated by Django 3.2.23 on 2024-01-02 09:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='v1699179858/lakyrzjrxgfb05kpyi2r', max_length=255, verbose_name='image'),
        ),
    ]
