# Generated by Django 3.2.23 on 2023-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_authoraccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authoraccessrequest',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
