# Generated by Django 3.2.23 on 2023-12-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('author', '0003_auto_20231229_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoraccessrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='authoraccessrequest',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
