# Generated by Django 3.2.23 on 2024-01-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20231229_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoraccessrequest',
            old_name='is_authorized',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='authoraccessrequest',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
