# Generated by Django 3.2.23 on 2024-01-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_profile_image'),
        ('author', '0005_auto_20240104_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoraccessrequest',
            old_name='is_approved',
            new_name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='authoraccessrequest',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='authormessage',
            name='author',
        ),
        migrations.AddField(
            model_name='authormessage',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
